//Driver types

const EndpointEnum = @import("endpoint.zig").EndpointEnum;

/// Availability and functions of each endpoint
pub const EPConfig = union(enum) {
    disabled,
    enabled: struct {
        max_packet_size: u16,
        supported_types: packed struct {
            bulk: bool = true,
            interrupt: bool = true,
            iso: bool = true,
        } = .{},
    },
};

/// Endpoint capabilities provided by the driver. excluding EP0!!!
///
/// each index corresponds to endpoint address + 1
pub const EndpointCapabilities = struct {
    /// If the driver has a maximum shared USB memory limit
    max_memory_bytes: ?u16 = null,
    EP0_max_size: u16,
    in: [15]EPConfig,
    out: [15]EPConfig,
};

pub const EPAssigned = union(enum) {
    unused,
    assigned: struct {
        transfer_type: EndpointEnum,
        packet_size: u16,
        gateway_num: u8,
    },
};

/// EP configurations generated by Config according to the rules defined by `EndpointCapabilities`. excluding EP0!!!
///
/// each index corresponds to endpoint address + 1
pub const ConfigAssignment = struct {
    in: [15]EPAssigned,
    out: [15]EPAssigned,

    pub fn init() ConfigAssignment {
        return ConfigAssignment{
            .in = @splat(.unused),
            .out = @splat(.unused),
        };
    }
};
