const std = @import("std");

pub const LANGID = enum(u16) {
    afrikaans = 0x0436,
    albanian = 0x041c,
    arabic_saudi_arabia = 0x0401,
    arabic_iraq = 0x0801,
    arabic_egypt = 0x0c01,
    arabic_libya = 0x1001,
    arabic_algeria = 0x1401,
    arabic_morocco = 0x1801,
    arabic_tunisia = 0x1c01,
    arabic_oman = 0x2001,
    arabic_yemen = 0x2401,
    arabic_syria = 0x2801,
    arabic_jordan = 0x2c01,
    arabic_lebanon = 0x3001,
    arabic_kuwait = 0x3401,
    arabic_uae = 0x3801,
    arabic_bahrain = 0x3c01,
    arabic_qatar = 0x4001,
    armenian = 0x042b,
    assamese = 0x044d,
    azeri_latin = 0x042c,
    azeri_cyrillic = 0x082c,
    basque = 0x042d,
    belarussian = 0x0423,
    bengali = 0x0445,
    bulgarian = 0x0402,
    burmese = 0x0455,
    catalan = 0x0403,
    chinese_taiwan = 0x0404,
    chinese_prc = 0x0804,
    chinese_hong_kong = 0x0c04,
    chinese_singapore = 0x1004,
    chinese_macau = 0x1404,
    croatian = 0x041a,
    czech = 0x0405,
    danish = 0x0406,
    dutch_netherlands = 0x0413,
    dutch_belgium = 0x0813,
    english_us = 0x0409,
    english_uk = 0x0809,
    english_australian = 0x0c09,
    english_canadian = 0x1009,
    english_new_zealand = 0x1409,
    english_ireland = 0x1809,
    english_south_africa = 0x1c09,
    english_jamaica = 0x2009,
    english_caribbean = 0x2409,
    english_belize = 0x2809,
    english_trinidad = 0x2c09,
    english_zimbabwe = 0x3009,
    english_philippines = 0x3409,
    estonian = 0x0425,
    faeroese = 0x0438,
    farsi = 0x0429,
    finnish = 0x040b,
    french_standard = 0x040c,
    french_belgian = 0x080c,
    french_canadian = 0x0c0c,
    french_switzerland = 0x100c,
    french_luxembourg = 0x140c,
    french_monaco = 0x180c,
    georgian = 0x0437,
    german_standard = 0x0407,
    german_switzerland = 0x0807,
    german_austria = 0x0c07,
    german_luxembourg = 0x1007,
    german_liechtenstein = 0x1407,
    greek = 0x0408,
    gujarati = 0x0447,
    hebrew = 0x040d,
    hindi = 0x0439,
    hungarian = 0x040e,
    icelandic = 0x040f,
    indonesian = 0x0421,
    italian_standard = 0x0410,
    italian_switzerland = 0x0810,
    japanese = 0x0411,
    kannada = 0x044b,
    kashmiri_india = 0x0860,
    kazakh = 0x043f,
    konkani = 0x0457,
    korean = 0x0412,
    korean_johab = 0x0812,
    latvian = 0x0426,
    lithuanian = 0x0427,
    lithuanian_classic = 0x0827,
    macedonian = 0x042f,
    malay_malaysia = 0x043e,
    malay_brunei = 0x083e,
    malayalam = 0x044c,
    manipuri = 0x0458,
    marathi = 0x044e,
    nepali_india = 0x0861,
    norwegian_bokmal = 0x0414,
    norwegian_nynorsk = 0x0814,
    oriya = 0x0448,
    polish = 0x0415,
    portuguese_brazil = 0x0416,
    portuguese_standard = 0x0816,
    punjabi = 0x0446,
    romanian = 0x0418,
    russian = 0x0419,
    sanskrit = 0x044f,
    serbian_cyrillic = 0x0c1a,
    serbian_latin = 0x081a,
    sindhi = 0x0459,
    slovak = 0x041b,
    slovenian = 0x0424,
    spanish_traditional = 0x040a,
    spanish_mexican = 0x080a,
    spanish_modern = 0x0c0a,
    spanish_guatemala = 0x100a,
    spanish_costa_rica = 0x140a,
    spanish_panama = 0x180a,
    spanish_dominican_rep = 0x1c0a,
    spanish_venezuela = 0x200a,
    spanish_colombia = 0x240a,
    spanish_peru = 0x280a,
    spanish_argentina = 0x2c0a,
    spanish_ecuador = 0x300a,
    spanish_chile = 0x340a,
    spanish_uruguay = 0x380a,
    spanish_paraguay = 0x3c0a,
    spanish_bolivia = 0x400a,
    spanish_el_salvador = 0x440a,
    spanish_honduras = 0x480a,
    spanish_nicaragua = 0x4c0a,
    spanish_puerto_rico = 0x500a,
    sutu = 0x0430,
    swahili_kenya = 0x0441,
    swedish = 0x041d,
    swedish_finland = 0x081d,
    tamil = 0x0449,
    tatar = 0x0444,
    telugu = 0x044a,
    thai = 0x041e,
    turkish = 0x041f,
    ukrainian = 0x0422,
    urdu_pakistan = 0x0420,
    urdu_india = 0x0820,
    uzbek_latin = 0x0443,
    uzbek_cyrillic = 0x0843,
    vietnamese = 0x042a,

    // HID class reserved
    hid_usage_data = 0x04ff,
    hid_vendor_defined_1 = 0xf0ff,
    hid_vendor_defined_2 = 0xf4ff,
    hid_vendor_defined_3 = 0xf8ff,
    hid_vendor_defined_4 = 0xfcff,
};

///regular string descriptors, the user can set a string for each language, if the language is not listed here, the fallback string will be used.
///note: the generator will only use the langagues that the device supports, so if the device does not support a language, the string for that language will not be included in the descriptor.
///in other words, setting a string for a language that the device does not support will have no effect, and the string will not be included in the descriptor.
///the generator also will deduplicate strings, so if two languages have the same string, only one will be included in the descriptor.
pub const USBStrings = struct {
    /// if the device uses a language that is not listed here, the fallback string will be used.
    /// if the fallback string is also null, the device will not provide a string descriptor.
    /// this applys to all string descriptors, including manufacturer, product and serial number.
    fallback: ?[]const u8 = null,

    afrikaans: ?[]const u8 = null,
    albanian: ?[]const u8 = null,
    arabic_saudi_arabia: ?[]const u8 = null,
    arabic_iraq: ?[]const u8 = null,
    arabic_egypt: ?[]const u8 = null,
    arabic_libya: ?[]const u8 = null,
    arabic_algeria: ?[]const u8 = null,
    arabic_morocco: ?[]const u8 = null,
    arabic_tunisia: ?[]const u8 = null,
    arabic_oman: ?[]const u8 = null,
    arabic_yemen: ?[]const u8 = null,
    arabic_syria: ?[]const u8 = null,
    arabic_jordan: ?[]const u8 = null,
    arabic_lebanon: ?[]const u8 = null,
    arabic_kuwait: ?[]const u8 = null,
    arabic_uae: ?[]const u8 = null,
    arabic_bahrain: ?[]const u8 = null,
    arabic_qatar: ?[]const u8 = null,
    armenian: ?[]const u8 = null,
    assamese: ?[]const u8 = null,
    azeri_latin: ?[]const u8 = null,
    azeri_cyrillic: ?[]const u8 = null,
    basque: ?[]const u8 = null,
    belarussian: ?[]const u8 = null,
    bengali: ?[]const u8 = null,
    bulgarian: ?[]const u8 = null,
    burmese: ?[]const u8 = null,
    catalan: ?[]const u8 = null,
    chinese_taiwan: ?[]const u8 = null,
    chinese_prc: ?[]const u8 = null,
    chinese_hong_kong: ?[]const u8 = null,
    chinese_singapore: ?[]const u8 = null,
    chinese_macau: ?[]const u8 = null,
    croatian: ?[]const u8 = null,
    czech: ?[]const u8 = null,
    danish: ?[]const u8 = null,
    dutch_netherlands: ?[]const u8 = null,
    dutch_belgium: ?[]const u8 = null,
    english_us: ?[]const u8 = null,
    english_uk: ?[]const u8 = null,
    english_australian: ?[]const u8 = null,
    english_canadian: ?[]const u8 = null,
    english_new_zealand: ?[]const u8 = null,
    english_ireland: ?[]const u8 = null,
    english_south_africa: ?[]const u8 = null,
    english_jamaica: ?[]const u8 = null,
    english_caribbean: ?[]const u8 = null,
    english_belize: ?[]const u8 = null,
    english_trinidad: ?[]const u8 = null,
    english_zimbabwe: ?[]const u8 = null,
    english_philippines: ?[]const u8 = null,
    estonian: ?[]const u8 = null,
    faeroese: ?[]const u8 = null,
    farsi: ?[]const u8 = null,
    finnish: ?[]const u8 = null,
    french_standard: ?[]const u8 = null,
    french_belgian: ?[]const u8 = null,
    french_canadian: ?[]const u8 = null,
    french_switzerland: ?[]const u8 = null,
    french_luxembourg: ?[]const u8 = null,
    french_monaco: ?[]const u8 = null,
    georgian: ?[]const u8 = null,
    german_standard: ?[]const u8 = null,
    german_switzerland: ?[]const u8 = null,
    german_austria: ?[]const u8 = null,
    german_luxembourg: ?[]const u8 = null,
    german_liechtenstein: ?[]const u8 = null,
    greek: ?[]const u8 = null,
    gujarati: ?[]const u8 = null,
    hebrew: ?[]const u8 = null,
    hindi: ?[]const u8 = null,
    hungarian: ?[]const u8 = null,
    icelandic: ?[]const u8 = null,
    indonesian: ?[]const u8 = null,
    italian_standard: ?[]const u8 = null,
    italian_switzerland: ?[]const u8 = null,
    japanese: ?[]const u8 = null,
    kannada: ?[]const u8 = null,
    kashmiri_india: ?[]const u8 = null,
    kazakh: ?[]const u8 = null,
    konkani: ?[]const u8 = null,
    korean: ?[]const u8 = null,
    korean_johab: ?[]const u8 = null,
    latvian: ?[]const u8 = null,
    lithuanian: ?[]const u8 = null,
    lithuanian_classic: ?[]const u8 = null,
    macedonian: ?[]const u8 = null,
    malay_malaysia: ?[]const u8 = null,
    malay_brunei: ?[]const u8 = null,
    malayalam: ?[]const u8 = null,
    manipuri: ?[]const u8 = null,
    marathi: ?[]const u8 = null,
    nepali_india: ?[]const u8 = null,
    norwegian_bokmal: ?[]const u8 = null,
    norwegian_nynorsk: ?[]const u8 = null,
    oriya: ?[]const u8 = null,
    polish: ?[]const u8 = null,
    portuguese_brazil: ?[]const u8 = null,
    portuguese_standard: ?[]const u8 = null,
    punjabi: ?[]const u8 = null,
    romanian: ?[]const u8 = null,
    russian: ?[]const u8 = null,
    sanskrit: ?[]const u8 = null,
    serbian_cyrillic: ?[]const u8 = null,
    serbian_latin: ?[]const u8 = null,
    sindhi: ?[]const u8 = null,
    slovak: ?[]const u8 = null,
    slovenian: ?[]const u8 = null,
    spanish_traditional: ?[]const u8 = null,
    spanish_mexican: ?[]const u8 = null,
    spanish_modern: ?[]const u8 = null,
    spanish_guatemala: ?[]const u8 = null,
    spanish_costa_rica: ?[]const u8 = null,
    spanish_panama: ?[]const u8 = null,
    spanish_dominican_re: ?[]const u8 = null,
    spanish_venezuela: ?[]const u8 = null,
    spanish_colombia: ?[]const u8 = null,
    spanish_peru: ?[]const u8 = null,
    spanish_argentina: ?[]const u8 = null,
    spanish_ecuador: ?[]const u8 = null,
    spanish_chile: ?[]const u8 = null,
    spanish_uruguay: ?[]const u8 = null,
    spanish_paraguay: ?[]const u8 = null,
    spanish_bolivia: ?[]const u8 = null,
    spanish_el_salvador: ?[]const u8 = null,
    spanish_honduras: ?[]const u8 = null,
    spanish_nicaragua: ?[]const u8 = null,
    spanish_puerto_rico: ?[]const u8 = null,
    sutu: ?[]const u8 = null,
    swahili_kenya: ?[]const u8 = null,
    swedish: ?[]const u8 = null,
    swedish_finland: ?[]const u8 = null,
    tamil: ?[]const u8 = null,
    tatar: ?[]const u8 = null,
    telugu: ?[]const u8 = null,
    thai: ?[]const u8 = null,
    turkish: ?[]const u8 = null,
    ukrainian: ?[]const u8 = null,
    urdu_pakistan: ?[]const u8 = null,
    urdu_india: ?[]const u8 = null,
    uzbek_latin: ?[]const u8 = null,
    uzbek_cyrillic: ?[]const u8 = null,
    vietnamese: ?[]const u8 = null,
    // HID clas: ?[]const u8 = null,
    hid_usage_data: ?[]const u8 = null,
    hid_vendor_defined_1: ?[]const u8 = null,
    hid_vendor_defined_2: ?[]const u8 = null,
    hid_vendor_defined_3: ?[]const u8 = null,
    hid_vendor_defined_4: ?[]const u8 = null,

    pub fn get_string(self: *const @This(), langid: LANGID) ?[]const u8 {
        return @field(self, @tagName(langid));
    }

    ///check if at least one string is set for the given langids, if not, check if the fallback string is set, if not, return false.
    pub fn check_string(self: *const @This(), langids: []const LANGID) bool {
        if (self.fallback != null) return true;
        for (langids) |langid| {
            if (self.get_string(langid) != null) return true;
        }
        return false;
    }
};

fn usb_len(comptime raw: []const u8) usize {
    const UTF16Len = comptime std.unicode.calcUtf16LeLen(raw) catch |err| {
        @compileError(std.fmt.comptimePrint("Failed to calculate UTF-16LE length: ", .{err}));
    };

    const total_len = (UTF16Len * 2) + 2; // +2 for length and descriptor type
    return total_len;
}
///Takes a Zig Literal string and converts it to a USB string descriptor, which is a UTF-16LE encoded string with a length prefix and a descriptor type byte.
pub fn StringToUSB(comptime raw: []const u8) [usb_len(raw)]u8 {
    comptime var string_desc: [usb_len(raw)]u8 = undefined;
    comptime {
        if (usb_len(raw) > 255) @compileError(std.fmt.comptimePrint("String is too long to be a USB string descriptor: {d}", .{usb_len(raw)}));
        string_desc[0] = @intCast(usb_len(raw));
        string_desc[1] = 0x03; // Descriptor type for string

        _ = std.unicode.utf8ToUtf16Le(@ptrCast(@alignCast(string_desc[2..])), raw) catch |err| {
            @compileError(std.fmt.comptimePrint("fail to convert string into UTF16LE, error : {}", .{err}));
        };
    }
    return string_desc;
}

test "string to string descriptor" {
    const foo = "Hello, World!";
    const bar = "some chinese: 你好，世界！";
    const foo_desc = StringToUSB(foo);
    const bar_desc = StringToUSB(bar);
    std.debug.print("foo_desc: {x}\n", .{foo_desc});
    std.debug.print("bar_desc: {x}\n", .{bar_desc});
}
