/// USB HID Boot Protocol keyboard usage IDs (Usage Page 0x07).
/// The first eight bytes of a boot keyboard report are modifiers, reserved,
/// and up to six values from this enum.
pub const ScanKey = enum(u8) {
    a = 0x04,
    b,
    c,
    d,
    e,
    f,
    g,
    h,
    i,
    j,
    k,
    l,
    m,
    n,
    o,
    p,
    q,
    r,
    s,
    t,
    u,
    v,
    w,
    x,
    y,
    z,

    key_1 = 0x1e,
    key_2,
    key_3,
    key_4,
    key_5,
    key_6,
    key_7,
    key_8,
    key_9,
    key_0,
    enter = 0x28,
    escape,
    backspace,
    tab,
    space,
    minus,
    equal,
    left_bracket,
    right_bracket,
    backslash,
    non_us_hash,
    semicolon,
    apostrophe,
    grave,
    comma,
    period,
    slash,
    caps_lock,

    f1 = 0x3a,
    f2,
    f3,
    f4,
    f5,
    f6,
    f7,
    f8,
    f9,
    f10,
    f11,
    f12,
    print_screen,
    scroll_lock,
    pause,
    insert,
    home,
    page_up,
    delete,
    end,
    page_down,
    right_arrow,
    left_arrow,
    down_arrow,
    up_arrow,

    num_lock = 0x53,
    keypad_divide,
    keypad_multiply,
    keypad_subtract,
    keypad_add,
    keypad_enter,
    keypad_1,
    keypad_2,
    keypad_3,
    keypad_4,
    keypad_5,
    keypad_6,
    keypad_7,
    keypad_8,
    keypad_9,
    keypad_0,
    keypad_decimal,
    non_us_backslash,
    application,
    power,
    keypad_equal,

    f13,
    f14,
    f15,
    f16,
    f17,
    f18,
    f19,
    f20,
    f21,
    f22,
    f23,
    f24,

    execute = 0x74,
    help,
    menu,
    select,
    stop,
    again,
    undo,
    cut,
    copy,
    paste,
    find,
    mute,
    volume_up,
    volume_down,

    locking_caps_lock = 0x82,
    locking_num_lock,
    locking_scroll_lock,
    keypad_comma,
    keypad_equal_sign,

    international_1 = 0x87,
    international_2,
    international_3,
    international_4,
    international_5,
    international_6,
    international_7,
    international_8,
    international_9,
    lang_1,
    lang_2,
    lang_3,
    lang_4,
    lang_5,
    lang_6,
    lang_7,
    lang_8,
    lang_9,

    alternate_erase = 0x99,
    sysreq_attention,
    cancel,
    clear,
    prior,
    return_key,
    separator,
    out,
    oper,
    clear_again,
    crsel,
    exsel,

    keypad_00 = 0xb0,
    keypad_000,
    thousands_separator,
    decimal_separator,
    currency_unit,
    currency_subunit,
    keypad_left_parenthesis,
    keypad_right_parenthesis,
    keypad_left_brace,
    keypad_right_brace,
    keypad_tab,
    keypad_backspace,
    keypad_a,
    keypad_b,
    keypad_c,
    keypad_d,
    keypad_e,
    keypad_f,
    keypad_xor,
    keypad_caret,
    keypad_percent,
    keypad_less_than,
    keypad_greater_than,
    keypad_ampersand,
    keypad_double_ampersand,
    keypad_vertical_bar,
    keypad_double_vertical_bar,
    keypad_colon,
    keypad_hash,
    keypad_space,
    keypad_at,
    keypad_exclamation,
    keypad_memory_store,
    keypad_memory_recall,
    keypad_memory_clear,
    keypad_memory_add,
    keypad_memory_subtract,
    keypad_memory_multiply,
    keypad_memory_divide,
    keypad_plus_minus,
    keypad_clear,
    keypad_clear_entry,
    keypad_binary,
    keypad_octal,
    keypad_decimal_mode,
    keypad_hexadecimal,

    left_control = 0xe0,
    left_shift,
    left_alt,
    left_gui,
    right_control,
    right_shift,
    right_alt,
    right_gui,
};

/// Modifier bits in byte 0 of a USB HID Boot Keyboard report.
pub const Modifier = packed struct(u8) {
    left_control: bool = false,
    left_shift: bool = false,
    left_alt: bool = false,
    left_gui: bool = false,
    right_control: bool = false,
    right_shift: bool = false,
    right_alt: bool = false,
    right_gui: bool = false,
};

pub const Report = struct {
    modifier: Modifier = .{},
    key_0: ?ScanKey = null,
    key_1: ?ScanKey = null,
    key_2: ?ScanKey = null,
    key_3: ?ScanKey = null,
    key_4: ?ScanKey = null,
    key_5: ?ScanKey = null,

    pub fn report(self: *const Report) [8]u8 {
        var hid_rep: [8]u8 = @splat(0);
        hid_rep[0] = @bitCast(self.modifier);

        inline for (@typeInfo(Report).@"struct".field_names[1..], 2..) |nf, idx| {
            hid_rep[idx] = if (@field(self, nf)) |sc| @backingInt(sc) else 0;
        }
        return hid_rep;
    }
};
